### ISSUE TITLE
`pip install sklearn-genetic-opt[all]` not working

### ISSUE THREAD

**Issue by mario-sanz** [rodrigo-arenas/Sklearn-genetic-opt#106]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04
Sklearn-genetic-opt  version: 0.9.0
Scikit-learn version: 1.1.2
Python version: 3.10.4 (with virtual environment)

**Describe the bug**
Hello. I am trying to get all the features of this package but the `pip install sklearn-genetic-opt[all]` command seems not to be working. I have tried to install it with and without `sklearn-genetic-opt` (basic package) installed but neither of them work. Do you know why this happens?

**To Reproduce**
This is the input and output of my console:
```
> pip install sklearn-genetic-opt[all]
zsh: no matches found: sklearn-genetic-opt[all]
```

**Expected behavior**
To get the package installed.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rodrigo-arenas** [comment]
Hi @mario-sanz, unfortunately this package doesn't support python 3.10+, this is because it's built on top of the DEAP, package, which doesn't support this python version, once they upgrade it I'll as well for sklearn-genetic-opt
