### ISSUE TITLE
[FEATURE] Support for XGBoost early stopping 

### ISSUE THREAD

**Issue by hrampadarath** [rodrigo-arenas/Sklearn-genetic-opt#108]
Thanks for such a cool package.

I'm using GASearchCV to hypertune an xgboost model. However, it is failing if I use early stopping an fit()
Can early stopping (and the additional xgbosst fitting params) be used with GASearchCV().fit()?

Thanks,
Hayden

**Comment by rodrigo-arenas** [comment]
Hi @hrampadarath, can you please provide a snippet of the code you're using and the error you get? This way it's easier to evaluate what is going on
