### ISSUE TITLE
GAFeatureSelectionCV - <classifier> object has no attribute 'transform'

### ISSUE THREAD

**Issue by RNarayan73** [rodrigo-arenas/Sklearn-genetic-opt#110]
**System information**
OS Platform and Distribution: Windows 11 Home
Sklearn-genetic-opt version: 0.9.0
deap version: 1.3.3
Scikit-learn version: 1.1.2
Python version: 3.8.13

**Describe the bug**
I have fitted an instance of GAFeatureSelectionCV using LGBMClassifier 
```
clf_dim = LGBMClassifier()
gen_opt = GAFeatureSelectionCV(
                               clf_dim, cv=5, scoring='avg_prec', refit=True, 
                               generations=20, population_size=50, tournament_size=3,
                               mutation_probability=0.8, crossover_probability=0.2, elitism=True, keep_top_k=1,
                               n_jobs=1, verbose=True, 
                              )
```
and got the expected results in the various output attributes such as .best_estimator_ and n_features_in_

However, unlike the example provided in the documentation, I am not attempting to use the selected features and the estimator directly to predict results on test data. 

Instead, I am trying to follow the traditional scikit-learn approach of incorporating this estimator to select features as step 'dim' in the following pipeline, before passing them on to another classifier at the end of the pipeline 
![image](https://user-images.githubusercontent.com/82275999/196409011-e40f6fcf-89c4-41c7-9a00-e45ea46588a7.png)

This requires that the 'transformer' based on GAFeatureSelectionCV supports a transform() method, which it does. However, when I try to use the transform method of the fitted estimator standalone, as in:
```
gen_opt.transform(X_t)
```
I get an error suggesting that 
> 'LGBMClassifier' object has no attribute 'transform'

I went on to define a pipeline with the estimator as below:
```
pipe_dim_full = Pipeline(
    steps=[
        ('enc', encode), 
        ('dim', gen_opt), 
        ('clf', clf), 
    ], 
)
```
and upon trying to fit it, I get a somewhat contradictory error:
> TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'GAFeatureSelectionCV(cv=StratifiedKFold(n_splits=5, random_state=0, shuffle=True),
>                      estimator=LGBMClassifier(n_jobs=1, random_state=0,
>                                               verbose=-1),
>                      generations=20, n_jobs=18, return_train_score=True,
>                      scoring=make_scorer(average_precision_score, needs_proba=True, pos_label=1))' (type <class 'sklearn_genetic.genetic_search.GAFeatureSelectionCV'>) doesn't
> 

As it stands, GAFeatureSelectionCV can't be used in a pipeline without the transform() method being fixed, which is unfortunate as I really like it and was looking forward to using GA across my pipeline.

**To Reproduce**
As described above. Please reach out if you need more detail.

**Expected behavior**
The transform method should product a matrix with n_features_in_ columns of the input matrix

**Additional context**
There is another module based on deap that successfully offers feature selection by genetic algorithm. Here is a link for reference [https://sklearn-genetic.readthedocs.io/en/latest/api.html](url)

**Comment by GiannisPikoulis** [comment]
Having exact same issue, this needs to be fixed.

**Comment by RNarayan73** [comment]
@rodrigo-arenas Hello, wondering if this is on your radar?

**Comment by rodrigo-arenas** [comment]
Hi @RNarayan73 @GiannisPikoulis 
The problem is not with the package itself but probably with how the estimator is been used, the sort answer is you must change your code from `gen_opt.transform(X_t)` to `gen_opt.predict(X_t)`, the detailed explanation is:

When you create a scikit-learn pipeline and you use the transform method, the base classifier must have this transform (not the GA but the LightGBM in this case) as in mentioned in the scikit-learn [pipeline documentation](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.transform)

![image](https://user-images.githubusercontent.com/31422766/217978501-34fea5ff-4061-405d-a2f1-7b24f385edfd.png)


If you check the [LightGBM docs](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html) you can see that it doesn't have any transform method, that is the error you are getting
![image](https://user-images.githubusercontent.com/31422766/217978698-cb1892b6-29f6-499c-bfc1-25d0df22d96a.png)

So overall, you should be calling the predict method after using GASearchCV, as mentioned in the scikit-learn docs, the predict method "Transform the data, and apply to predict with the final estimator."
![image](https://user-images.githubusercontent.com/31422766/217978939-2d2a4669-46bb-4bda-9d6d-dc858a92fd8e.png)

I hope it makes it clear

**Comment by RNarayan73** [comment]
@rodrigo-arenas thanks for your speedy reply.

I'm a user of the libraries and not a developer, so can't comment accurately as to the structure of genetic-search-opt. Maybe, the 3rd party library sklearn-genetic-opt may not be a suitable example, as I haven't investigated it's internal code. All I can say is how they are supposed to behave based on my experience with applying both SKL and non-SKL libraries to build ML models.

From reading your reply above, it appears that you are modelling GAFeatureSelectionCV and GASearchCV in the same manner by inheriting from the BaseSearchCV class because of the common cross-validated search aspect they share. They are however, meant to serve different functions. GAFeatureSelectionCV is meant to output a set of features (or some criteria that allows selection of a subset of the features), while GASearchCV is meant for hyperparameter optimisation by wrapping a predictor or a pipeline with a predictor at the end. Therefore, GAFeatureSelectionCV should be a transformer (based on what it outputs, not based on how the search is carried out) unlike GASearchCV.

The closest that SKL itself has to GAFeatureSelectionCV, which outputs a reduced feature set with cross-validation is the class RFECV standing for Recursive Feature Elimination with CV. However, a cursory look at the code for RFECV suggests that it doesn't use BaseSearchCV class. It appears BaseSearchCV is used only with predictors at the end. While it is suitable for GASearchCV, it may not be the right approach for GAFeatureSelectionCV, which is a transformer based on its intended output. 
RFECV shows how ScikitLearn does a cross-validation without BaseSearchCV class for transformers. I would encourage you to align the class definition of GAFeatureSelectionCV to RFECV which will enable it to do perform its intended function properly. i.e. output a revised set of features within a pipeline and pass it on to a predictor such as LinearSVC or DecisionTreeRegressor to enable prediction.
(I admit, I may be out of my depth here in terms of the technical implementation, but I am confident as to how they are supposed to behave, i.e. a feature selector is a transformer which should have a transform method in order to modify the feature set before it is passed on to a different predictor at the end of the pipeline).


> Could you share the full code snippet running the pipeline without sklearn-genetic-opt and using the transform method?

Below, I've shared snippets with pipeline with a wrapper transformer for feature selection using 3 different options to transform features and yield some feature selection criteria. You can try them all out and see that RFECV and GeneticSelectionCV work, while GAFeatureSelectionCV fails.
```
test_pipe_noclf = Pipeline([
                        # 1 Feature Selection using GAFeatureSelectionCV
#                             ('dim', GAFeatureSelectionCV(LGBMClassifier(), 
#                                                          generations=5, population_size=5, 
#                                                          n_jobs=JOBS, 
#                                                         )
#                             ), 

                        # 2 Feature Selection using RFECV
                            ('dim', RFECV(LGBMClassifier())), 

                        # 3 Feature Selection using GeneticSelectionCV
#                             ('dim', GeneticSelectionCV( LGBMClassifier(),                               
#                                                         n_generations=5, n_gen_no_change=3, n_population=5, 
#                                                         n_jobs=JOBS, caching=True
#                                                       )
#                             ), 
                           ]
                          )

test_pipe_noclf.fit(iris.data, iris.target)

test_pipe_noclf.transform(iris.data)
```
The following snippet does the same with a classifier at the end and wrapped in GridSearchCV, which allows you to run a predict, again with the same results.
```
from sklearn.datasets import load_iris

from lightgbm import LGBMClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import RFECV
from sklearn_genetic import GAFeatureSelectionCV
from genetic_selection import GeneticSelectionCV

iris = load_iris()

test_pipe = Pipeline([
                    # 1 Feature Selection using GAFeatureSelectionCV
#                       ('dim', GAFeatureSelectionCV(LGBMClassifier(), 
#                                                    generations=5, population_size=5, 
#                                                    n_jobs=JOBS, 
#                                                   )
#                       ), 
                        
                    # 2 Feature Selection using RFECV
                      ('dim', RFECV(LGBMClassifier())), 
                        
                    # 3 Feature Selection using GeneticSelectionCV
#                       ('dim', GeneticSelectionCV( LGBMClassifier(),                               
#                                                   n_generations=5, n_gen_no_change=3, n_population=5, 
#                                                   n_jobs=JOBS, caching=True
#                                                 )
#                       ), 
                      
                      ('clf', SGDClassifier())
                     ]
                    )

grid_search_pipe = GridSearchCV(test_pipe, 
                                param_grid={'clf__alpha': [1e-04, 1e-03, 1e-02, 1e-01, 1e+00]}, 
                                verbose=1
                               )

grid_search_pipe.fit(iris.data, iris.target)

grid_search_pipe.predict(iris.data)
```

In respect of **your** code snippets above, the pipeline 'pipe' in both end with a classifier - DecisionTreeRegressor and LinearSVC respectively. Hence they will not take a transform method, only a predict method whether they are called directly as in the first case or within GridSearchCV as in the second case.

However, the StrandardScaler(), MinMaxScaler, PCA, SelectKBest etc. are transformers and when they are executed standalone i.e. without a pipe, they will have a transform method, but not a predict method. Even when they are within a pipeline but without a classifier at the end, they will take a transform as I have demonstrated in my 1st snippet above.
PCA and SelectKBest are feature selection transformers which change the feature set within the pipeline before a predictor works on the modified matrix. Similarly, GAFeatureSelectionCV, GeneticSelectionCV and RFECV can also sit in the 'reduce_dim' step of the 2nd code snippet above, before the final predictor to select a subset of features, but only as a transformer.

I hope I have helped clarify the intended functionality of SKL transformers, predictors and how search with cv may be different for both.

Feel free to reach out to me if you have further questions,

Regards
Narayan

**Comment by rodrigo-arenas** [comment]
Hi @RNarayan73 I think I missunderstood something, you were talking about GAFeatureSelectionCV and I was replying as GASearchCV is meant to work
I think it makes more sence now, I'll try to improve the general workflow so It's easier to use GAFeatureSelectionCV with the scikit-learn pipelines

**Comment by rodrigo-arenas** [comment]
Hi @RNarayan73 
I've changed the GAFeatureSelectionCV API in PR #124  so it's similar to the FeatureSelection algorithms from scikit-learn, now it's possible to use the transform and other methods directly without having to transform manually the X input to get the selected features

This will be available in the next release that will come later this week, feel free to check how this will work, [here](https://sklearn-genetic-opt.readthedocs.io/en/latest/notebooks/Iris_feature_selection.html) there is an example of how to use the GAFeatureSelectionCV after this change

As a recap, now you can use it like this:

```python 
evolved_estimator.fit(X_train, y_train)

# Features selected by the algorithm
features = evolved_estimator.support_
print(features)

# Predict only with the subset of selected features
y_predict_ga = evolved_estimator.predict(X_test)
print(accuracy_score(y_test, y_predict_ga))
```
