### ISSUE TITLE
Issue: Documentation reference in GAFeatureSelectionCV

### ISSUE THREAD

**Issue by ion-elgreco** [rodrigo-arenas/Sklearn-genetic-opt#116]
Documentation is referring to the wrong methods for GAFeatureSelectionCV: https://github.com/rodrigo-arenas/Sklearn-genetic-opt/blob/5ca13c47e9a2b91f78cb59e98d0ac872e226e26b/docs/api/featureselectioncv.rst

![image](https://user-images.githubusercontent.com/15728914/210659825-ad32ba7a-40af-4688-a0e5-8901dac1f544.png)

**Comment by Plutone11011** [comment]
Hi, I would like to fix this, if possible. Seems like a good first issue to solve.

**Comment by rodrigo-arenas** [comment]
Hi @Plutone11011 thanks, go ahead

**Comment by rodrigo-arenas** [comment]
This was fixed in PR #121, it will be available in the stable docs with the next release
