### ISSUE TITLE
[FEATURE] Using numpy array instead of Python list to describe selected features of an individual

### ISSUE THREAD

**Issue by juju21555** [rodrigo-arenas/Sklearn-genetic-opt#133]
Hi,

It seems that the selected features of an individual is stored in a Python list of 0 and 1 (1 if the feature is selected else 0).
This can lead to performance and memory issue, when dealing with thousands of features/individuals.

It may be interesting to have an option to store it in a numpy array instead. 
The numpy array would only store the index of the selected features (e.g. : [1, 4, 5] instead of [0, 1, 0, 0, 1, 1]) 

Because numpy indexing of boolean array are known to be slower than using an index array when the ratio of selected features over total features is low.

I forked the project and implemented this in the `GAFeatureSelectionCV` class, using the attribute `use_numpy_array`.
You can try it yourself. I recreated the `Iris_feature_selection.ipynb` with thousands of random features to test it under the name `Large_feature_selection.ipynb`.

Let me know if you think it could be interesting to add it in your project and I will do a pull request.
Also, I'd be glad to listen to your advice about this new feature.

**Comment by rodrigo-arenas** [comment]
Hi @juju21555, thanks!
I think is a good idea to enhance the performance of the class, in this case, I don't see the necessity to use the parameter `use_numpy_array`, we can leave it just as the default (and only) behavior, so we can avoid the use a lot of if/else statements for this variable
We just have to make sure to keep the current format for the variable `support_`, this is to be consistent with the sckit-learn API

But internally all the optimization, cross-over and other operations can be updated to use this format and only at the end update the variable `support_` with the old (current) format

**Comment by rodrigo-arenas** [comment]
Closing this issue for now, let me know if it's something you might want to work
