### ISSUE TITLE
Cannot install from conda-forge into Python 3.11 environment even with all dependencies met

### ISSUE THREAD

**Issue by RNarayan73** [rodrigo-arenas/Sklearn-genetic-opt#138]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 Pro
Sklearn-genetic-opt  version: 0.10.1
Scikit-learn version: 1.3.0
Python version: 3.11.4
deap version: 1.4.1
numpy version: 1.24.3
tqdm version: 4.65.0

**Describe the bug**
Despite dependencies satisfied for deap, scikit-learn, numpy, the following error occurs:

> Collecting package metadata (current_repodata.json): done
> Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> Package python conflicts for:
> python=3.11
> sklearn-genetic-opt -> python[version='>=3.8']
> sklearn-genetic-opt -> deap[version='>=1.3.3'] -> python[version='3.10.*|3.9.*|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.6|3.8.*|3.7.*|3.6.*|>=2.7|>=3.7']
> 

**To Reproduce**
1. Run `conda create -n test python=3.11 sklearn-genetic-opt -d`

**Expected behavior**
No error should occur when installing from conda-forge into a Python 3.11 environment

**Screenshots**
N/A

**Additional context**
However, installing through pip from pypi works fine

**Comment by rodrigo-arenas** [comment]
Hi @RNarayan73 , if possible open an issue in this repo, since the conda package is not directly managed here, but is automatically generated by the conda-forge project: https://github.com/conda-forge/staged-recipes

**Comment by RNarayan73** [comment]
@rodrigo-arenas done, thanks for the steer

**Comment by RNarayan73** [comment]
@rodrigo-arenas, update from conda-forge repo https://github.com/conda-forge/staged-recipes/issues/24079

**Comment by rodrigo-arenas** [comment]
Hi, unfortunately, this is managed by conda itself, and they currently doesn't support tensorflow for windows out to the box, which will make the package installation fail
