### ISSUE TITLE
[DOCS]  English Tutorials Review

### ISSUE THREAD

**Issue by rodrigo-arenas** [rodrigo-arenas/Sklearn-genetic-opt#43]
**Is your feature request related to a problem? Please describe.**
Currently there are several tutorials in the docs. As English is my second language, it probably has some errors and redaction that can be improved.

**Describe the solution you'd expect**
I'd appreciate if someone could review and improve the tutorials documentation to make it clearer to English readers.

Check the docs/tutorials files and make the changes that be necessary

**Comment by rhit-namburs** [comment]
Hi! I would like to work on this issue as I am a native English speaker.

**Comment by rodrigo-arenas** [comment]
Hi @rhit-namburs, thanks, I'll assign you this issue, I apareciste the help!

**Comment by rodrigo-arenas** [comment]
Closing now after several improvements, if anyone finds an opportunity, feel free to open a PR with the changes
