### ISSUE TITLE
[FEATURE] GAFeaturesSelectionCV

### ISSUE THREAD

**Issue by rodrigo-arenas** [rodrigo-arenas/Sklearn-genetic-opt#56]
**Is your feature request related to a problem? Please describe.**
This feature will make the package extend it's functionalities to include feature selection using evolutionary algorithms. Currently, only hyperparameters tuning is being done.

**Describe the solution you'd expect**

Implement the class GAFeaturesSelectionCV inside sklearn_genetic.genetic_search with the following functionalities:

* This function should take the same parameters as GASearchCV except for param_grid, the estimator should have it's own defined parameters.
* Perform cross-validation over different set of features that are selected using evolutionay algorithms. The same sklean_genetic.algorithms options must be available as optimization routine.
* The class should be able to work with the existing features of the package, such as Callbacks, plot fitness evolution.
* All the documentation must be updated, indicating which functionallity of the package is compatible only with GASearchCV (e.g most likely plot_search_space won't be compatible with feature selection).
* It must accepts a GASearchCV instance as the estimator.
* There must be an attribute called best_features_ that has the final selected features by the model.

**Additional context**
The evolutionary algorithm can be defined by assigning a gen to each parameter, if the gen is 1, it means the parameters is selected, 0 otherwise.

**Note:** I'll be working on this feature, but as always, new ideas and contributions to this is welcome

**Comment by das-ankur** [comment]
Hello, I want to work on this too? Can I?

**Comment by rodrigo-arenas** [comment]
Hello, yes you can, this is probably the hardest feature available, so I'll be working on it as well, just to make sure it's compatible with all the package, I'll do it on a new branch named FeaturesSelectionCV, so make sure to clone this branch and make the PR on it

**Comment by rodrigo-arenas** [comment]
This feature is implemented in PR #79 and will be available in version 0.7.0
