### ISSUE TITLE
[FEATURE] Add threshold parameter to ConsecutiveStopping

### ISSUE THREAD

**Issue by poroc300** [rodrigo-arenas/Sklearn-genetic-opt#64]
**Is your feature request related to a problem? Please describe.**
I ran `GASearchCV`  with a callback that stopped the optimization if the fitness was no greater than at least one value of fitness from the last 5 generations.

```
callback = ConsecutiveStopping(generations=5, metric='fitness')
```
Checking the log information while the algorithm was running, I have noticed that the reported fitness (-12.7893) was the same for more than 5 consecutive generations (please see the attached image). Under these circumstances, I would have expected the algorithm to have stopped much earlier (in generation 8).

![consecutive_stopping](https://user-images.githubusercontent.com/8134662/124898719-5ad80000-dfd7-11eb-81c1-91df73d9b73a.png)

I assume the algorithm did not stop because the logbook only shows 4 decimal places. However, given that fitness improved very little after generation 8, I think in some situations the user could have the option to provide a threshold value to `ConsecutiveStopping`, which would make the algorithm to stop after N consecutive generations if the improvement in fitness (or any other metric) was no greater than a specific threshold (e.g. 0.0001). This could make the algorithm to finish much faster in some occasions. 

**Describe the solution you'd expect**
I have made a custom callback (which hopefully is correct) to achieve what I want (the documentation was quite helpful). Please feel free to make any comments regarding my code:

```
from sklearn_genetic.callbacks.base import BaseCallback

class ConsecutiveStoppingThreshold(BaseCallback):
    def __init__(self, threshold, N, metric='fitness'):
        self.threshold = threshold
        self.N = N
        self.metric = metric
        
    def on_step(self, record, logbook, estimator=None):
        #not enough data points
        if len(logbook) <= self.N:
            return False
        
        #get the last N metrics
        stats = logbook.select(self.metric)[-self.N :]
        
        #find the difference between max and min fitness in the last metrics
        diff = max(stats) - min(stats)
        
        if self.threshold > diff:
            return True
        return False
```

I have tested this code and it appears to work fine. In my perspective, such type of callback is very useful and, therefore, I think it should be more easily accessible to users. In my opinion, you could do one of the following:

1. Show an explicit example, in the section "Custom callbacks" in the package's homepage, where you demonstrate how to achieve the above.
2. Or have a `threshold` argument in `ConsecutiveStopping` where the user can provide a float to determine how much improvement is allowed after N consecutive generations.

**Comment by rodrigo-arenas** [comment]
Hi, thanks for your report and suggestion
Effectively, this is because of the precision that python can handle when comparing two float points.
What you are trying to achieve, would probably be a better fit for the `DeltaThreshold` callback, it stops the training if the absolute difference between the current and last generation metric is not greater than a threshold parameter `abs(current_stat - previous_stat) <= self.threshold`
It's used like this:

```python
from sklearn_genetic.callbacks import DeltaThreshold
callback = DeltaThreshold(threshold=0.001, metric='fitness')

evolved_estimator.fit(X, y, callbacks=callback)
```

I could add the parameter generations (N) to control how many to compare, and make it 2 by default, to keep the current default logic.

**Comment by poroc300** [comment]
Yes, `DeltaThreshold` could be also an interesting option. Thanks for addressing this.

**Comment by rodrigo-arenas** [comment]
No problem, I'm glad to help, this is now implemented in the master branch and it will be released in the next version.
