### ISSUE TITLE
 change [FEATURE]

### ISSUE THREAD

**Issue by Fancy-angel** [rodrigo-arenas/Sklearn-genetic-opt#76]
Main Features:
GASearchCV: Principal class of the package, holds the evolutionary cross-validation optimization routine.
Algorithms: Set of different evolutionary algorithms to use as an optimization procedure.
Callbacks: Custom evaluation strategies to generate early stopping rules, logging (into TensorBoard, .pkl files, etc) or your custom logic.
Plots: Generate pre-defined plots to understand the optimization process.
MLflow: Build-in integration with mlflow to log all the hyperparameters, cv-scores and the fitted models

**Comment by Fancy-angel** [comment]
I want to work on this issue  @rodrigo-arenas  please merge it with me.

**Comment by rodrigo-arenas** [comment]
Hi @Fancy-angel , all the help is welcome!
Sorry, I don't quite understand, which feature you wanna work on? All that list is what is already in the package

Bu there are some open issues that need help, let me know if you have any question

Greetings

**Comment by rodrigo-arenas** [comment]
Closing this issue, as mentioned, you can work on issue #27
