### ISSUE TITLE
Version attribute does not seem to work

### ISSUE THREAD

**Issue by rasbt** [rodrigo-arenas/Sklearn-genetic-opt#80]
**System information**
OS Platform and Distribution (e.g., macOS 12.0.1):
Sklearn-genetic-opt  version: Unknown
Scikit-learn version: 1.0
Python version: 3.9

**Describe the bug**
The version attribute does not seem to work

**To Reproduce**
```python
import sklearn_genetic
print(sklearn_genetic.__version__)
```

**Expected behavior**
Should show version number.

**Screenshots**
![Screen Shot 2021-11-21 at 8 18 01 AM](https://user-images.githubusercontent.com/5618407/142765474-05ef2ea2-967a-4ff2-a895-5b5bdc5b4dd9.png)

**Additional context**
Installed package as described in the docs, i.e., 

```
pip install sklearn-genetic-opt
```

**Comment by rasbt** [comment]
Nvm. Pip installed an old version from pypi which didn't have the version attribute. Downloading the source code and installing it from the local location fixed it.

**Comment by rodrigo-arenas** [comment]
The self-solving bugs are the best, let me know if you have any questions!
